services:

  mysql:
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --log-bin --binlog-format=ROW  --server-id=2 --sync-binlog=1 --binlog-annotate-row-events=0 --log-bin-trust-function-creators=ON"
    volumes:
      - "${SQL_SCRIPTS_PATH}/mysql/zz_01_kenyaemr_facility_wide_updated_concepts_dump_2024_02_06.sql:/docker-entrypoint-initdb.d/zz_01_kenyaemr_facility_wide_updated_concepts_dump_2024_02_06.sql"
      - "${SQL_SCRIPTS_PATH}/mysql/zz_03_drug_2023-10-25.sql:/docker-entrypoint-initdb.d/zz_03_drug_2023-10-25.sql"
      - "${SQL_SCRIPTS_PATH}/mysql/zz_04_update_tablet_units.sql:/docker-entrypoint-initdb.d/zz_04_update_tablet_units.sql"
      - "${SQL_SCRIPTS_PATH}/mysql/zz_05_skip_liquibase_schema_scripts.sql:/docker-entrypoint-initdb.d/zz_05_skip_liquibase_schema_scripts.sql"
